### ISSUE TITLE
App Permissions by IzzySoft

### ISSUE THREAD

**Issue by shuvashish76** [Hamza417/Inure#358]
> https://github.com/Hamza417/Inure/blob/master/community/permissions/community_permissions_guide.md

Detailed collection list is already available by @IzzySoft : https://android.izzysoft.de/applists/perms

I think better to use this collection which has all the relevant reference.

**Comment by shuvashish76** [comment]
@IzzySoft you mentioned in your [mastodon](https://floss.social/@IzzyOnDroid) profile that posts are licensed under CC BY-NC-SA, which includes your site articles & this list as well?

**Comment by IzzySoft** [comment]
permissions_guide: that's a nice idea and could serve as a good source (as it has a well defined format and the JSON could be evaluated automatically) – but with only 4 permissions a bit short, and lacking details like "practical implications" unfortunately. The latter also is the problem with official documentation: after 15 years, and 10+ years running my app lists, I still wonder how devs find out what permission they need for what purpose. And it seems many devs wonder the same…

Unfortunately, my app list will always be incomplete. Hard to keep up with what new Android versions introduce – especially when details are so hard to find. I have a "second table" in my database collecting "unknown permissions" (and which app uses them). From time to time I check that for new permissions used by multiple apps, and see what I can add. Often takes about an hour for a single permission, to find details sufficient to at least give an idea what it is about…

> posts are licensed under CC BY-NC-SA, which includes your site articles & [App Lists](https://android.izzysoft.de/applists.php)?

Even my books, yes.

**Comment by Hamza417** [comment]
The community permission description is an initiative to create a database of obscure OEM and App permissions whose description can't be found in the firmware. There can be exceptions, but it's not meant for default Android Permissions because their info is already baked in the rom by default. This project also has a [complete ID list of Android permissions](https://github.com/Hamza417/Inure/blob/master/app/src/main/resources/permissions.txt) extracted directly from [AOSP source file](https://android.googlesource.com/platform/frameworks/base/+/master/core/res/AndroidManifest.xml) using [this script](https://github.com/Hamza417/Inure/blob/master/scripts/permissions/permission_extractor.py).

Here's an example of such permissions.

![6154199398410729971](https://github.com/user-attachments/assets/d1c02182-aea9-481d-a898-f2f391714e14)
